import MobileMainNav from "@/components/mobile-main-nav";
import SiteAside from "@/components/site-aside";
import SiteHeader from "@/components/site-header";
export const metadata = {
  title: "Sevdem Maya - Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="relative flex flex-row overflow-hidden lg:overflow-visible">
      <SiteAside />
      <main className="flex max-w-full flex-1 flex-col">
        <SiteHeader />
        <MobileMainNav />
        <div className="p-4 py-6 md:px-8">{children}</div>
      </main>
    </div>
  );
}
