import SiteAside from "@/components/site-aside";
import SiteHeader from "@/components/site-header";

export const metadata = {
  title: "Sevdem Maya - Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="relative flex min-h-screen flex-row">
      <SiteAside />
      <main className="flex flex-1 flex-col gap-1 pb-10">
        <SiteHeader />
        {children}
      </main>
    </div>
  );
}
