import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs/app-beta";
import ToastContainerWrapper from "../components/ui/ToastContainerWrapper";
import { cn } from "@/lib/utils";
import { inter } from "@/lib/fonts";

export const metadata = {
  title: "Template",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    { rel: "icon", url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    { rel: "apple-touch-icon", url: "/apple-touch-icon.png", sizes: "180x180" },
  ],
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="tr">
        <body className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}>
          {children}
          <ToastContainerWrapper />
        </body>
      </html>
    </ClerkProvider>
  );
}
